### ISSUE TITLE
line_df not defined in README.md

### ISSUE THREAD

**Issue by trashbirdecology** [bbc/bbplot#12]
The dataframe used to plot the example, `line_df` is not defined. 

Perhaps create an example df and save to the package, or provide code in .md to create `line_df`.

**Comment by hlj-datacamp** [comment]
The line_df dataframe is a filtered down version of the gapminder dataset. This comes with an R install and can be accessed by putting `library(gapminder)` at the top of your code :)

**Comment by trashbirdecology** [comment]
Thanks for the clarification. It may be useful to, in README.md, define the line_df, as whatever subset of `gapminder` you prefer, such that the "typical workflow" code chunk can be run directly. May also be useful to rename line_df --> my_line_plot. 

E.g. 👍 
`line_df = gapminder %>% filter(country == "Afghanistan")  ` 
`my_line_plot <- ggplot(line_df, aes(x = year, y = lifeExp)) +`
`geom_line(colour = "#007f7f", size = 1) +`
`geom_hline(yintercept = 0, size = 1, colour="#333333") +`
`bbc_style()`
`finalise_plot(plot_name = my_line_plot,
             source = "Source: ONS",
             save_filepath = "filename_that_my_plot_should_be_saved_to-nc.png",
             width_pixels = 640,
             height_pixels = 550)`


Just a thought. Thanks for the pkg!

**Comment by trashbirdecology** [comment]
I now see that someone has submitted a pr; (https://github.com/bbc/bbplot/pull/2), so I will close this:
